name: Maintain a language
description: Request to become a maintainer
title: "maintain: <language>"
labels: []
body:
  - type: input
    id: language
    attributes:
      label: What language do you want to maintain?
      description: You will be in charge of reviewing strings and can assist in assigning roles
    validations:
      required: true
  - type: input
    id: discord-id
    attributes:
      label: Discord ID
      description: Used for record-keeping and roles
    validations:
      required: true
